### ISSUE TITLE
 My skin is not displayed after adding Loliasm

### ISSUE THREAD

**Issue by JourneyIM** [LoliKingdom/LoliASM#144] opened 2022-10-11 11:11 UTC
With loliasm, my skin becomes standard, that is, Steve's skin. How do I fix this?
![2022-10-11_16 07 44](https://user-images.githubusercontent.com/111415056/195075154-7a828d70-3c96-4ddc-9aec-347ff2a81cce.png)

**Comment by Rongmario** [comment] 2022-10-30 09:58
Duplicate of https://github.com/LoliKingdom/LoliASM/issues/125, disable `fixMC186052` for now, fixed in next version.

**Closed by Rongmario** 2022-10-30 09:58 UTC
