### ISSUE TITLE
Fix HWYLA's crash when looking at villagers

### ISSUE THREAD

**Issue by xemnes** [LoliKingdom/LoliASM#94] opened 2022-05-07 16:12 UTC
getting mass crash spam (because the game doesnt close on crash lol) when looking at villagers, 
crash report seems to point to waila
https://pastes.dev/bm2I0kHsNY

double checked to see if it happens without loliasm and it doesnt.

edit: wait nope. i think im wrong
https://pastebin.com/sJjKCDt4
log is being spammed, just no crash report popping up.

edit2: looked at the code in an ide, i dont get it... the field exists

**Comment by embeddedt** [comment] 2022-05-07 23:54
> i dont get it... the field exists

The deobfuscated field only exists in your development environment. At runtime, it should be using `field_175563_bv` (the SRG name) instead. One of your mods must think the game is running in dev for some reason.

**Comment by xemnes** [comment] 2022-05-07 23:59
hmmm that would be rather odd, though im fairly sure this is hwyla/waila thats at fault here
but the reflection used does state both the obfuscated and deobfuscated field, 'careerId' is apparently the field that doesnt exist. i wondered if perhaps it was changed in later mappings, but nope.
![image](https://user-images.githubusercontent.com/603338/167275949-cb41e450-b320-4250-8648-d497ac0c2af7.png)

**Comment by Rongmario** [comment] 2022-05-08 08:40
I think this bug only surfaced because of LoliASM's deobfuscation mapper optimization.

**Comment by xemnes** [comment] 2022-05-08 11:06
im not sure thats the case, if its happening without loliasm then surely its a problem with hwyla? the problem happened in the dev environment of hwylas source, i didnt add loliasm when i was testing it. seems the reflection code in the mod was truly incorrect.

**Comment by Rongmario** [comment] 2022-05-08 11:15
That's because deobfuscation doesn't taken place in the dev env, hence why it'd happen in dev too.

**Comment by xemnes** [comment] 2022-05-08 11:18
hmmm, ok. perhaps i just dont fully understand it.

**Comment by embeddedt** [comment] 2022-05-08 12:20
Despite the `ReflectionHelper` code being seemingly incorrect, I can't seem to reproduce it in a regular instance with only LoliASM (5.2) and Hwyla installed. I ran `/summon villager` then looked at the villager. No errors were logged for me.

**Comment by xemnes** [comment] 2022-05-08 12:26
thats really odd
https://github.com/TehNut-Mods/HWYLA/blob/1.12/src/main/java/mcp/mobius/waila/addons/minecraft/HUDHandlerVillager.java
the code does seem to be incorrect in the source, the fields being in the wrong places. ive tested with and without loliasm, just hwyla on its own and in dev and the outcome is always the same. console will be spammed with the field not existing.
swapping the fields then compiling and testing fixes the problem for me.

**Comment by embeddedt** [comment] 2022-05-08 12:27
This is a long shot but what Java version are you using?

**Comment by xemnes** [comment] 2022-05-08 12:28
1.8.0_331

**Comment by embeddedt** [comment] 2022-05-08 12:30
That's close enough to mine (I have 332). You have no other mods installed besides LoliASM when this happens?

**Comment by xemnes** [comment] 2022-05-08 12:31
happens with or without loliasm

**Comment by Rongmario** [comment] 2022-05-08 12:35
The plot thickens... What's your mod list? Would HWYLA on its own replicate it?

**Comment by xemnes** [comment] 2022-05-08 12:36
hmmm, i do wonder if the source is the problem, could it be that it was changed in the source and the release version on curseforge is different? i do run a custom version of hwyla, but ive not touched the reflection code. my version just changes the hud to show energy as a bar (well it does to a certain degree, im stuggling to replicate the one probes code, the bar doesnt show on every tile entity that has energy capability and i dont know why)
![image](https://user-images.githubusercontent.com/603338/167296401-34a54b5b-2481-489a-9db1-31f082b5431f.png)

**Comment by embeddedt** [comment] 2022-05-08 12:36
@xemnes Where did you get your custom Hwyla from? I can decompile it and check.

**Comment by xemnes** [comment] 2022-05-08 12:37
i got it from here 
https://github.com/TehNut-Mods/HWYLA/tree/1.12
as far as im aware, its the original source

**Comment by embeddedt** [comment] 2022-05-08 12:38
Okay, I'm using the release version so I'll decompile that one to compare.

**Comment by embeddedt** [comment] 2022-05-08 12:40
No, looks like the code is exactly the same:

```java
int careerId = ReflectionHelper.getPrivateValue(EntityVillager.class, (EntityVillager)ent, new String[]{"field_175563_bv", "careerId"});
```

**Comment by xemnes** [comment] 2022-05-08 12:41
can you try running in dev to see if the problem occurs there?

**Comment by xemnes** [comment] 2022-05-08 13:02
just pushed my changes to my fork if you want to test that https://github.com/xemnes/HWYLA/tree/1.12

**Comment by xemnes** [comment] 2022-05-08 13:13
> The plot thickens... What's your mod list? Would HWYLA on its own replicate it?

it does indeed https://gfycat.com/mistyplainblackrussianterrier
i reverted the change i made that fixes it to show
i can however confirm it doesnt happen with the version from curseforge, it only happens with a version compiled from the source.
im using intellij idea with gradle to compile the source, also tested it with a completely unmodified version of the source and the same thing happens.

**Comment by Rongmario** [comment] 2022-05-11 12:12
Closing bc the custom HWYLA build can resolve this issue.

**Closed by Rongmario** 2022-05-11 12:12 UTC
Labels: enhancement

**Comment by xemnes** [comment] 2022-05-11 12:15
huh, i thought i had closed it in my last comment due to my conclusion. sorry about that.

**Comment by Rongmario** [comment] 2022-05-11 12:20
No problem!
