### ISSUE TITLE
LoliASM breaks Railcraft's charge system

### ISSUE THREAD

**Issue by xJon** [LoliKingdom/LoliASM#131] opened 2022-08-17 22:34 UTC
As the title mentions. Really odd.

Without LoliASM:
Place Rock Crusher down, place admin charge feeder unit (w/ redstone signal), and it will be powered.

With LoliASM the same setup or any attempt to power Railcraft's machine that use its "charge" power will not work.

(Tested with just Railcraft, HEI & LoliASM installed)

**Comment by Rongmario** [comment] 2022-08-17 22:42
Duplicate of #127

**Comment by xJon** [comment] 2022-08-17 22:42
Seems to be a duplicate of https://github.com/LoliKingdom/LoliASM/issues/127, didn't see it, sorry!

**Closed by Rongmario** 2022-08-17 22:42 UTC
Labels: bug
