### ISSUE TITLE
Crash when using Loliasm, Atum 2, and Apotheosis

### ISSUE THREAD

**Issue by KnightCa** [LoliKingdom/LoliASM#195] opened 2023-08-02 20:26 UTC
I was able to run and play (without errors) including:
* Minecraft: 1.12.2
* Forge: 14.23.5.2860
* MixinBooter: 8.3
* Atum 2: 2.0.20
* Apotheosis: 1.12.5
* Placebo: 1.6.1 (dependency for Apotheosis)
All mods are on the latest version available.

When adding the following mod, Minecraft crashes while starting:
* CensoredASM (Loliasm): 5.14
Crash Log: https://gist.github.com/KnightCa/64735a90972fd9d022f452985b2bf7e4

**Comment by Rongmario** [comment] 2023-09-11 16:41
Duplicate of #136, fixed in v6

**Closed by Rongmario** 2023-09-11 16:41 UTC
Labels: v6-fix
