### ISSUE TITLE
Client starts fine but server crashes.

### ISSUE THREAD

**Issue by dazadazu** [LoliKingdom/LoliASM#11] opened 2021-05-09 06:27 UTC
[crash-reports_crash-2021-05-08_20.44.27-server.txt](https://github.com/LoliKingdom/LoliASM/files/6447032/crash-reports_crash-2021-05-08_20.44.27-server.txt)

Latest 2.3 version

**Comment by Rongmario** [comment] 2021-05-10 12:44
Duplicate of #9

**Closed by Rongmario** 2021-05-10 12:44 UTC
