### ISSUE TITLE
'makeEventsSingletons' makes crash with thaumcraft

### ISSUE THREAD

**Issue by rebarakuk** [LoliKingdom/LoliASM#119] opened 2022-07-10 11:28 UTC
When there should be main menu screen after forge loading, the crash happens

If makeEventsSingletons=false, crash disappears

[crash report](https://gist.github.com/rebarakuk/f6710cf3769b3f7ec3c720bea8d64867)

[latest log](https://gist.github.com/rebarakuk/1bde4686f7cc5c549fcca6a5138f19d5)

Also, I wanna know what options in config decrease fps or unstablize tps (because if I don't make almost every option false, fps drops. Not only options noted 'This can induce slowdowns' drop fps, but others do too)

So I'll ask you to post them on CurseForge Description

And if you also post what options are good for fps and tps, I'll be thankful

**Comment by Rongmario** [comment] 2022-07-11 17:59
Duplicate of https://github.com/LoliKingdom/LoliASM/issues/103.

As for your question, the config comments should explain enough. I'll note things in there if something affects fps/tps immensely. There's not many FPS optimizations in here, I am working on this however: https://github.com/CleanroomMC/Blackbox

**Closed by Rongmario** 2022-07-11 17:59 UTC

**Comment by Rongmario** [comment] 2023-09-26 01:21
This has now been fixed.
