### ISSUE TITLE
Texture/animation bug together with OptiFine

### ISSUE THREAD

**Issue by NorthHusky** [LoliKingdom/LoliASM#110] opened 2022-05-31 11:48 UTC
Mods:
preview_OptiFine_1.12.2_HD_U_G6_pre1
loliasm-5.3
!mixinbooter-4.2
Chisel-MC1.12.2-1.0.2.45
CTM-MC1.12.2-1.0.2.31
gregtech-1.12.2-2.3.1-beta

1) Such a problem is present when the Anisotropic filtering parameter is set in Optifine [1-16]
And in the config of your mod, two parameters are set to True:
```
textures {
    # Calculate and send animated textures only when needed to the GPU, better than VanillaFix's textureFixes config - <default: true>
    B:onDemandAnimatedTextures=true

    # Releases TextureAtlasSprite's framesTextureData. Won't touch custom TextureAtlasSprite implementations - <default: true>
    B:releaseSpriteFramesCache=true
```
    
![image](https://user-images.githubusercontent.com/105886827/171163891-bce53cb6-04a5-4246-8243-680d545a688c.png)

2) With these parameters in the config, there is a bug in the animation of the fan blocks from the Chisel mod (missing fan rotation animation)
![image](https://user-images.githubusercontent.com/105886827/171165209-4ceca191-09d9-4ca8-a9e9-cef758ea23ac.png)

If you disable these two parameters in the config to False, or disable Anisotropic filtering to 0, then the bug does not appear
![image](https://user-images.githubusercontent.com/105886827/171165024-3bee8fcc-7d43-4b3b-ba39-657857d7561b.png)
![image](https://user-images.githubusercontent.com/105886827/171166156-781e4968-dc0b-4c11-ae9c-4dad67a45db9.png)
![image](https://user-images.githubusercontent.com/105886827/171166229-004de98e-0833-4ec0-b8d9-8dd210dad43e.png)

I need to disable these two parameters in the config and it should be like this, or is it a bug?

**Comment by Rongmario** [comment] 2022-05-31 11:53
Duplicate of #109

**Closed by Rongmario** 2022-05-31 11:53 UTC
