### ISSUE TITLE
Incompatibility with Vanilla Fix

### ISSUE THREAD

**Issue by RodrigoTaipe93** [LoliKingdom/LoliASM#100] opened 2022-05-13 00:56 UTC
Hello, I tried the mod with a small group of mods (focused on performance) and I got this crash:

- https://paste.ee/p/yn218

**Comment by ChAoSUnItY** [comment] 2022-05-13 01:13
Probably a duplicate of #88.

**Closed** 2022-05-14 19:37 UTC
