### ISSUE TITLE
Animated Textures are broken in Tinkers' Construct Smeltery

### ISSUE THREAD

**Issue by Desempregago** [LoliKingdom/LoliASM#63] opened 2022-01-10 21:31 UTC
Plus, I don't know what I can toggle in the config to alleviate this

https://user-images.githubusercontent.com/14002834/148842538-4807f8d2-b856-4aa1-808d-569536f2b439.mp4

**Comment by Desempregago** [comment] 2022-01-10 21:32
The molten metal is supposed to be flowing down, not being static

**Comment by Desempregago** [comment] 2022-01-10 21:32
Using LoliASM v4.4

**Comment by Rongmario** [comment] 2022-01-11 00:36
Try disabling `releaseSpriteFramesCache`.

**Comment by xJon** [comment] 2022-04-04 19:49
Can confirm this is happening also with version 4.8.

**Comment by Rongmario** [comment] 2022-04-05 00:20
Even when `releaseSpriteFramesCache` is false?

**Comment by xJon** [comment] 2022-04-05 02:43
@Rongmario Sorry for the misunderstanding - I did not test it beyond the default configuration, I will try to with your suggestion soon.

**Comment by Rongmario** [comment] 2022-04-05 09:35
That's no problem.

**Comment by xJon** [comment] 2022-04-05 14:31
@Rongmario I can confirm this is still an issue with `releaseSpriteFramesCache` disabled.

**Comment by Rongmario** [comment] 2022-04-05 18:16
What about disabling `squashBakedQuads`?

**Comment by xJon** [comment] 2022-04-05 23:34
@Rongmario Still an issue with `squashBakedQuads` disabled.

**Comment by Rongmario** [comment] 2022-04-05 23:34
Quite marvellous. I hate Tinkers' Construct.

**Comment by xJon** [comment] 2022-04-05 23:37
@Rongmario Wait, I think more testing is necessary - I just completely removed LoliASM and this is still an issue 👀

**Comment by Rongmario** [comment] 2022-04-05 23:39
Do you have VanillaFix installed?

**Comment by xJon** [comment] 2022-04-05 23:41
I do - and I can see where this is going

**Comment by Rongmario** [comment] 2022-04-05 23:42
Do you have `textureFixes` enabled for VF? Provided you're not using the dynamic model loading version of VF.

**Comment by xJon** [comment] 2022-04-05 23:44
I do have `textureFixes` enabled, and I can see that this issue with VanillaFix and Tinkers animated textures was reported in the past but I guess was never fully resolved - https://github.com/DimensionalDevelopment/VanillaFix/issues/39#issuecomment-439508499

**Comment by Rongmario** [comment] 2022-04-05 23:45
Yeah, I'm going to fix this soon, got way too many projects going on atm. Even a VanillaFix fork/rework is on the table.

**Comment by xJon** [comment] 2022-04-05 23:47
@Rongmario No worries, this is not your or your mod's responsibility, but thank you for the will to help make modded Minecraft better! If you do rework VanillaFix I'd be sure to include it in my modpacks, and I am currently testing LoliASM.
About this issue, you can probably close it as it is a VanillaFix issue.

**Comment by Rongmario** [comment] 2022-04-05 23:50
Thank you, but I think I'll keep it open for the time being as I think `releaseSpriteFramesCache` may have the same effect as VF's `textureFixes`. However, they don't quite do the same thing.

Also, I'm joined with quite a few others on trying to make 1.12.2 modded better w/ more support, we are quite ambitious: https://cleanroommc.com/

**Comment by xJon** [comment] 2022-04-06 00:59
I tested Tinkers' Construct with LoliASM, without VanillaFix, and this issue is not present - the textures animate properly.
And, that's awesome - I joined your Discord server!

**Comment by Rongmario** [comment] 2022-04-06 11:45
Oh? Good news. I always thought LoliASM had something to do with it...

**Closed by Rongmario** 2022-04-06 11:45 UTC
Labels: bug, mod_incompatibility

**Comment by embeddedt** [comment] 2022-04-06 12:48
For the record, I believe disabling `textureFixes` from VanillaFix will reduce the FPS substantially on AMD GPUs due to the fact that reuploading the textures each frame is extremely slow on them, unless `releaseSpriteFramesCache` does the same thing. Even on my Nvidia card I have found this VanillaFix optimization to actually be quite effective; when profiling the slowness in 1.16 I noticed that uploading animated textures took up a substantial part of the frame time. The VanillaFix beta for 1.16 made that issue go away.

**Comment by Rongmario** [comment] 2022-04-06 13:00
Yeah, I think I see exactly why VF's `textureFixes` makes this happen. I'll jot this down for when I'm working on the fork. It's also possible that I'd just work up something similar or better in https://github.com/CleanroomMC/Blackbox/
