### ISSUE TITLE
Config is ignoring code

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [LoliKingdom/LoliASM#16] opened 2021-05-25 10:32 UTC
[25/05/2021 05:30:51 AM] [Client thread/WARN]: class com.creativemd.creativecore.client.rendering.model.CreativeBakedQuad needs their BakedQuad calls redirecting! Insert the string into config/loliasm.json and report to Rongmario.

Config

# Configuration file

bakedquad {
    # Classes where BakedQuad::new calls need to be redirected - <default: [net.minecraft.client.renderer.block.model.FaceBakery]>
    S:classesThatCallBakedQuadCtor <
        net.minecraft.client.renderer.block.model.FaceBakery
        com.creativemd.creativecore.client.rendering.model.CreativeBakedQuad
        com.pixelmonmod.pixelmon.client.render.item.ItemRendererShrineOrb
     >

happens when I stare at the little bench

![2021-05-25_05 32 01](https://user-images.githubusercontent.com/10351221/119483431-944ff700-bd1a-11eb-8caf-207a40c93054.png)

**Comment by P3rf3ctXZer0** [comment] 2021-05-25 10:32
https://paste.atlauncher.com/view/8fcf0ff2-c345-47e8-a663-58b9fddcf7cd

**Comment by Rongmario** [comment] 2021-05-25 13:31
Duplicate of #15.

**Closed by Rongmario** 2021-05-25 13:31 UTC
