### ISSUE TITLE
Not animated textures.

### ISSUE THREAD

**Issue by Pineappleguy03** [LoliKingdom/LoliASM#112] opened 2022-06-03 02:24 UTC
Issue that I came across. It disables all moving textures... And even when I turn it off. It starts to heavily lag. You should let some animated textures be loaded in. Like Visible Blocks.

**Comment by Pineappleguy03** [comment] 2022-06-03 02:28
Another Note is that it disables ALL animated textures. Like Fire.

**Comment by Rongmario** [comment] 2022-06-03 02:36
Cannot replicate, are you using Optifine?

**Comment by Pineappleguy03** [comment] 2022-06-03 03:34
I am indeed using Optifine. But Animated Textures is on.

**Comment by Rongmario** [comment] 2022-06-03 07:41
Duplicate of #109

**Closed by Rongmario** 2022-06-03 07:41 UTC
Labels: question
