### ISSUE TITLE
HBM fluid doesn't have a color anymore

### ISSUE THREAD

**Issue by viqua** [LoliKingdom/LoliASM#66] opened 2022-03-31 22:11 UTC
when using the mod along with HBM nuclear tech mod reloaded all liquids (in their "drops" format) miss colors and appear only as white drops instead:
![2022-04-01_00 08 48](https://user-images.githubusercontent.com/102560145/161157559-d05e84e1-1dc1-4c77-b798-3312b1fe25a0.png)
![2022-04-01_00 09 12](https://user-images.githubusercontent.com/102560145/161157574-1b6bc732-d05d-4b77-97ac-93f6ce442733.png)
anyway to fix this?

**Comment by kappa-maintainer** [comment] 2022-04-25 16:43
I am building a near 300 mods modpack but can't reproduce, maybe not only loliasm cause this
![2022-04-26_00 36 51](https://user-images.githubusercontent.com/11038263/165134970-d38e682d-9bee-4d2a-8908-6b7f7047ec5e.png)

**Comment by Rongmario** [comment] 2022-04-25 16:48
I'll close this for now then, thank you.

**Closed by Rongmario** 2022-04-25 16:48 UTC
Labels: bug, mod_incompatibility
