### ISSUE TITLE
[Delegated to Blackbox] Animated Textures won't animate, such as Items, Fluids, etc.

### ISSUE THREAD

**Issue by Z-Tunic** [LoliKingdom/LoliASM#113] opened 2022-06-04 01:50 UTC
Prob a dupe issue but I dunno if item textures were mentioned.

Minecraft: 1.12.2
Forge: 14.23.5.2860

Optifine is NOT, installed.

Mods: 9
!mixinbooter-4.2
[___MixinCompat-0.8___]
Baubles-1.12-1.5.2
Botania+r1.10-362
GottschCore-mc1.12.2-f14.23.5.2859-v1.15.0
HadEnoughItems_1.12.2-4.22.0
loliasm-5.3
Nyx-1.5.1
Treasure2-mc1.12.2-f14.23.5.2859-v2.0.1

Log:
[latest.log](https://github.com/LoliKingdom/LoliASM/files/8836602/latest.log)

Debug:
[debug.log](https://github.com/LoliKingdom/LoliASM/files/8836603/debug.log)

---

For some reason, some modded item textures won't animate at all and will remain static. I used the above mods as examples since they have animated item textures.

![2022-06-03 20-28-47](https://user-images.githubusercontent.com/36653806/171971923-c26981be-2cf6-41fe-8e7a-413f70c750a9.gif)
The items won't animate if ASM is installed.

![2022-06-03 20-34-06](https://user-images.githubusercontent.com/36653806/171971925-e63e5c3c-0119-4bba-b7e6-8fc844dfeb41.gif)
The items will animate if ASM isn't installed.

If `onDemandAnimatedTextures` is set to false, the item textures will animate correctly. Also some other notes, I saw that some fluids inside the tinker smeltery were also static-like, though this also happened with the original Vanillafix mod.

They also remain static in the JEI / HEI Menu.

**Comment by Exaxxion** [comment] 2022-06-04 02:04
Probably half of the recent reports are "Textures aren't animating with the setting that disables textures animations on" / "closed as duplicate of #109".

**Comment by Z-Tunic** [comment] 2022-06-04 02:14
Yea, but I encountered this without having Optifine installed, and I dunno if they mentioned items having the issue along with the other stuff.

My apologies if this is a duplicated issue.

**Comment by lesdmark** [comment] 2022-06-09 09:49
I am also having this issue. Currently happening in the GTCEu Port of Nomi. Noticed that the Nomicoins looked weird and investigated and found that all the content tweaker animated textures were frozen. turning off the setting mentioned in #109 fixes it.

**Comment by Vetpetmon** [comment] 2022-06-13 17:29
`[13:26:47] [Client thread/ERROR] [minecraft/TextureMap]: Using missing texture, unable to load minecraft:textures/textures/atlas/blocks.png.png, java.io.FileNotFoundException`

A lot of files are trying to load `.png.png`

**Comment by Rongmario** [comment] 2022-06-13 17:31
That sounds like a Thaumcraft issue.

**Comment by Vetpetmon** [comment] 2022-06-13 17:45
UPDATE: We have a workaround.

Disable `onDemandAnimatedTextures` in your `.cfg` file. It's all the way down to the bottom of the file.

**Comment by Rongmario** [comment] 2022-06-13 17:46
I mean, this was mentioned several times in this exact thread and on other issue threads.

**Comment by Rongmario** [comment] 2022-07-24 10:53
@Vetpetmon do you have logs for when you saw the duplicate `.png` suffix errors?

**Closed** 2022-07-24 11:03 UTC
Labels: bug

**Comment by reddvilzz** [comment] 2022-07-25 04:22
Sorry to post on closed issue here, with the new update for the onDemandAnimatedTextures if optifine is used, it still need to be set to false?

**Comment by Rongmario** [comment] 2022-07-25 16:00
Yes I believe so.

**Comment by BinBashBanana** [comment] 2023-08-07 20:07
For those with optifine+*asm+foamfix, you may need to set `enable=false` under `textures` in foamfix.cfg if you are encountering extreme client tick lag with `onDemandAnimatedTextures=false`.
